### ISSUE TITLE
Included bottle incompatible with python3.8+

### ISSUE THREAD

**Issue by captbuckrogers25** [seem8/astech#1]
Attempting to run raises an error as 3.8+ requires the 'digestmod' parameter.

Installing the current bottle and removing the included 'bottle.py' solves the issue.

Suggested fix: either state bottle as a dependency or include an updated bottle.py

(As a side note, this is a really cool package.  It makes organizing MegaMek servers much easier)

**Comment by seem8** [comment]
Thanks. I bundled Bottle within the project to avoid people some trouble.
Bottle is updated now and works with Python 3.12.

**Comment by seem8** [comment]
Closing now. It took only 3 years.
